import { readFile, writeFile } from "fs/promises";
import { resolve } from "path";
import openapiTS from "openapi-typescript";

async function main() {
  const spec = await readFile(resolve("openapi/tmdb.v3.json"), "utf8");
  const out = await openapiTS(spec, {
    bannerComment:
      `/* eslint-disable */\n` + `// AUTO-GENERATED by openapi/codegen.ts — DO NOT EDIT.\n`,
  });
  await writeFile(resolve("src/generated/tmdb.ts"), out);
  console.log("✅ Wrote src/generated/tmdb.ts");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
